In [47]:
import numpy as np

In [21]:
data = np.array([
    [0.5, -0.2, 0.8],  # Day 1
    [0.1, 0.4, -0.3],  # Day 2
    [-0.6, 0.7, 0.2],  # Day 3
    [0.9, -0.1, 0.5],  # Day 4
    [-0.3, 0.0, -0.8]   # Day 5
])

1. Days 2 to 4:
 [[ 0.1  0.4 -0.3]
 [-0.6  0.7  0.2]
 [ 0.9 -0.1  0.5]]

In [5]:
data[1:4]

array([[ 0.1,  0.4, -0.3],
       [-0.6,  0.7,  0.2],
       [ 0.9, -0.1,  0.5]])

2. Asset 1 and 3:
 [[ 0.5  0.8]
 [ 0.1 -0.3]
 [-0.6  0.2]
 [ 0.9  0.5]
 [ 0.3 -0.8]]

In [8]:
data[:, [0,2]]

array([[ 0.5,  0.8],
       [ 0.1, -0.3],
       [-0.6,  0.2],
       [ 0.9,  0.5],
       [ 0.3, -0.8]])

3. Scores > 0.5:
 [0.8 0.7 0.9]

In [10]:
data[data > 0.5]

array([0.8, 0.7, 0.9])

4. Scores > 0.2 for asset 2:
 [0.4 0.7]

In [16]:
assets_2 = data[:, 1]
assets_2[assets_2 > 0.2]

array([0.4, 0.7])

5. Days where asset 1's score is negative:
 [[-0.6  0.7  0.2]]

In [22]:
data[data[:, 0] < 0]

array([[-0.6,  0.7,  0.2],
       [-0.3,  0. , -0.8]])

In [23]:
prices = np.array([
    [100, 150, 200],
    [110, 145, 210],
    [105, 155, 195],
    [115, 160, 205]
])

6. Mean prices per asset:
 [107.5 152.5 202.5]

In [28]:
mean_prices = np.mean(prices, axis=0)
mean_prices

array([107.5, 152.5, 202.5])

7. Centered prices (prices - mean):
 [[ -7.5  -2.5  -2.5]
 [  2.5  -7.5   7.5]
 [ -2.5   2.5  -7.5]
 [  7.5   7.5   2.5]]

In [30]:
centered_prices = prices - mean_prices
centered_prices

array([[-7.5, -2.5, -2.5],
       [ 2.5, -7.5,  7.5],
       [-2.5,  2.5, -7.5],
       [ 7.5,  7.5,  2.5]])

8. Percentage change from day 1:
 [[  0.           0.           0.        ]
 [ 10.          -3.33333333   5.        ]
 [  5.           3.33333333  -2.5       ]
 [ 15.           6.66666667   2.5       ]]

In [38]:
initial_prices = prices[0]
persentage_change = ((prices - initial_prices ) / initial_prices)  *100
persentage_change

array([[ 0.        ,  0.        ,  0.        ],
       [10.        , -3.33333333,  5.        ],
       [ 5.        ,  3.33333333, -2.5       ],
       [15.        ,  6.66666667,  2.5       ]])

9. Scaled prices (10% increase):
 [[110. 165. 220.]
 [121. 159.5 231.]
 [115.5 170.5 214.5]
 [126.5 176. 225.5]]

In [39]:
scaled_prices = prices * 1.1
scaled_prices

array([[110. , 165. , 220. ],
       [121. , 159.5, 231. ],
       [115.5, 170.5, 214.5],
       [126.5, 176. , 225.5]])

In [50]:
data = np.array([
    [0.5, np.nan, 0.8],
    [0.1, 0.4, -0.3],
    [-0.6, 0.7, 2.5],  # Outlier in last column
    [0.9, -0.1, 0.5],
    [np.nan, 0.0, -0.8]
])

10. Column means (ignoring NaN):
 [ 0.225  0.25   0.54 ]

In [52]:
column_means = np.nanmean(data, axis=0)
column_means

array([0.225, 0.25 , 0.54 ])

11. Data with NaN replaced by column means:
 [[ 0.5    0.25   0.8  ]
 [ 0.1    0.4   -0.3  ]
 [-0.6    0.7    2.5  ]
 [ 0.9   -0.1    0.5  ]
 [ 0.225  0.     -0.8  ]]

In [54]:
data_filled = np.where(np.isnan(data), column_means, data)
data_filled

array([[ 0.5  ,  0.25 ,  0.8  ],
       [ 0.1  ,  0.4  , -0.3  ],
       [-0.6  ,  0.7  ,  2.5  ],
       [ 0.9  , -0.1  ,  0.5  ],
       [ 0.225,  0.   , -0.8  ]])

12. Lower bound:
 [-0.8625 -0.55  -1.4625]

Upper bound:
 [ 1.2125  0.75   1.6625]

In [55]:
Q1 = np.percentile(data_filled, 25, axis=0)
Q3 = np.percentile(data_filled, 75, axis=0)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
print(f'lower bound: {lower_bound}')
print(f'upper bound: {upper_bound}')

lower bound: [-0.5  -0.6  -1.95]
upper bound: [1.1  1.   2.45]
